### ISSUE TITLE
'utf-8' codec can't decode byte 0x89 in position 0 Error

### ISSUE THREAD

**Issue by demib72** [Psycoguana/SubredditMediaDownloader#1]
Hello, I am currently having an issue with the script. When I get to a set point, I get the following error:

Traceback (most recent call last):
  File "/home/mharris89/Programs/SubredditMediaDownloader/main.py", line 312, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/mharris89/Programs/SubredditMediaDownloader/main.py", line 299, in main
    await downloader.run()
  File "/home/mharris89/Programs/SubredditMediaDownloader/main.py", line 54, in run
    elements = await self.get_elements_info(submissions, total_submissions)
  File "/home/mharris89/Programs/SubredditMediaDownloader/main.py", line 138, in get_elements_info
    link = await self.get_real_gif_link(sub.url)
  File "/home/mharris89/Programs/SubredditMediaDownloader/main.py", line 168, in get_real_gif_link
    data = data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

The beginning of the byte file is b'\x89PNG\r\n\x1a (cutting out the rest). Using python 3.10

**Comment by demib72** [comment]
Figured the problem, it can't handle loading in a png in byte form. An if statement returning a blank list if the mp4 has been removed/deleted seems to do the trick for now.

**Comment by Psycoguana** [comment]
Hey! Could you tell me on which subreddit this happens? Or the url of the png?

**Comment by demib72** [comment]
I rather not say the subreddit publicly. But the url of the removed content is https://i.imgur.com/6QsRyw9.gifv

**Comment by Psycoguana** [comment]
I couldn't manage to get an error using that link. If you want send me an email at nico@nico-dev.me with the subreddit or another image that fails and I'll take a look

**Comment by demib72** [comment]
Will do.

**Comment by coenvlietstra** [comment]
Good Morning

Has this been resolved yet?

**Comment by coenvlietstra** [comment]
Line 167 of main.py:

added try except:

``
try:
                data = data.decode('utf-8')
                match = re.findall(r'content="(.+mp4)', data)
            except:
                return ''
``

**Comment by Psycoguana** [comment]
Fixed by #4
