### ISSUE TITLE
AttributeError: 'submission' object has no attribute 'url'

### ISSUE THREAD

**Issue by coenvlietstra** [Psycoguana/SubredditMediaDownloader#2]
Exec time: 0.90 minutes.
Traceback (most recent call last):
  File "/Users/coenraadvlietstra/Downloads/SubredditMediaDownloader-main/main.py", line 313, in <module>
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/coenraadvlietstra/Downloads/SubredditMediaDownloader-main/main.py", line 300, in main
    await downloader.run()
  File "/Users/coenraadvlietstra/Downloads/SubredditMediaDownloader-main/main.py", line 54, in run
    elements = await self.get_elements_info(submissions, total_submissions)
  File "/Users/coenraadvlietstra/Downloads/SubredditMediaDownloader-main/main.py", line 135, in get_elements_info
    if re.search(r'\.(jpg|gif|png)$', sub.url):
AttributeError: 'submission' object has no attribute 'url'

Solution:

If statement at line 135:
``
if hasattr(sub, 'url'):
``

**Comment by Psycoguana** [comment]
Fixed by #4
