### ISSUE TITLE
Script crashing on specific post

### ISSUE THREAD

**Issue by Firq-ow** [Psycoguana/SubredditMediaDownloader#9]
Thanks for this great utility, it makes archiving a lot easier.

However, I am currently trying to archive a subreddit, but somehow the script keeps crashing on one specific post:

- Subreddit: r/scathach
- Post number is 297 according to the progress bar

Don't really know how to go on from here, as I am unsure what exactly causes this error. One thing could be (from the error paths) that the venv and my normal python installation interfere, but I think that's unlikely. The same issue also occurs in a venv on C

Full trace
```
Traceback (most recent call last):
  File "D:\General\archiver\subredditMediaDownloader\main.py", line 366, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\General\archiver\subredditMediaDownloader\main.py", line 353, in main
    await downloader.run()
  File "D:\General\archiver\subredditMediaDownloader\main.py", line 55, in run
    elements = await self.get_elements_info(submissions, total_submissions)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\General\archiver\subredditMediaDownloader\main.py", line 140, in get_elements_info
    if re.search(r'\.(jpg|gif|png)$', sub.url):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\re\__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

![image](https://user-images.githubusercontent.com/75133068/235777667-b5a4b6ad-2678-41de-879f-fd1e067374fd.png)

**Comment by Psycoguana** [comment]
Hi! Thanks for opening the issue.

PushShift hasn't been working too well lately, so for the moment I can't debug it. I'll push a fix as soon as possible.
